apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-controller-server-tcp
  namespace: default
spec:
  selector:
    matchLabels:
      name: network-controller-server-tcp
  template:
    metadata:
      labels:
        name: network-controller-server-tcp
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: network-controller-server-tcp
        image: sdnvortex/network-controller:v0.4.5
        securityContext:
          privileged: true
        command: ["/go/bin/server"]
        args: ["-tcp=0.0.0.0:50051"]
        volumeMounts:
        - mountPath: /var/run/docker/netns:shared
          name: docker-ns
          #mountPropagation: Bidirectional
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /var/run/openvswitch/
          name: ovs-data
      volumes:
      - name: docker-ns
        hostPath:
          path: /run/docker/netns
      - name: docker-sock
        hostPath:
          path: /run/docker.sock
      - name: ovs-data #for some operations(dump ports) it needs extra unix socker to handle, so we mount whole ovs directory
        hostPath:
          path: /run/openvswitch/
      hostNetwork: true
